version: "3.9"

services:
#  mongodb:
#    image: mongo:latest
#    container_name: mongodb
#    restart: unless-stopped
##    command: ["--replSet", "rs0", "--bind_ip_all"]
#    ports:
#      - "27018:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
#    volumes:
#      - mongo-data-v2:/data/db

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped


volumes:
#  mongo-data-v2:
  redis_data: