spring:
  application:
    name: journalApp
  data:
    mongodb:
#      uri: mongodb://chirayu:Chirayu@localhost:27018/testdb?authSource=admin
      uri: ${MONGO_URL}
      auto-index-creation: true
  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SEND_EMAIL} # give from sender email.
    password: ${APP_PASSWORD} # google Security App password can work fine.
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
